/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

// See https://docusaurus.io/docs/site-config for all the possible
// site configuration options.

// Define this so it can be easily modified in scripts (to host elsewhere)
const baseUrl = '/';

// If true, include Algolia search bar when building site
// Note: this setting is toggled to false by publish_site.sh script, so
// it should not be renamed without modifying that script.
const includeAlgolia = true;

// List of projects/orgs using your project for the users page.
const users = [];

const siteConfig = {
  title: 'PPLBench', // Title for your website.
  tagline: 'Evaluating Probabilistic Programming',
  url: 'https://pplbench.org',
  baseUrl: baseUrl,
  cleanUrl: true, // No .html extensions for paths

  // used for publishing and more
  projectName: 'pplbench',
  organizationName: 'facebookresearch',

  // Google analytics
  // gaTrackingId: '',

  // links that will be used in the header navigation bar
  headerLinks: [
    { doc: 'introduction', label: 'Docs' },
    { page: 'help', label: 'Help' },
    { blog: true, label: 'Blog' },
  ],

  headerLinks: [
    { doc: 'introduction', label: 'Docs' }, 
    { href: 'https://github.com/facebookresearch/pplbench', label: 'GitHub' },
  ],

  // add users to the website
  users,

  // images for header/footer and favicon
  headerIcon: 'img/pplbench_logo_full_color.png',
  footerIcon: 'img/favicon.png',
  favicon: 'img/favicon.png',

  // colors for website
  colors: {
    primaryColor: '#f29837', // orange
    secondaryColor: '#f0bc40', // yellow
  },

  highlight: {
    theme: 'default',
  },

  // custom scripts that are placed in <head></head> of each page
  scripts: [
    // Github buttons
    'https://buttons.github.io/buttons.js',
    // Copy-to-clipboard button for code blocks
    `${baseUrl}js/code_block_buttons.js`,
    'https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js',
    // Mathjax for rendering math content
    `${baseUrl}js/mathjax.js`,
    'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_HTML',
  ],

  // CSS sources to load
  stylesheets: [`${baseUrl}css/code_block_buttons.css`],

  // enable on-page navigation for the current documentation page
  onPageNav: 'separate',

  // enable scroll to top button a the bottom of the site
  scrollToTop: true,

  // if true, expand/collapse links & subcategories in sidebar
  docsSideNavCollapsible: false,

  // URL for editing docs
  editUrl: 'https://github.com/facebookresearch/pplbench/tree/master/docs/',

  // Open Graph and Twitter card images
  ogImage: 'img/favicon.png',
  twitterImage: 'img/favicon.png',

  // show html docs generated by sphinx
  wrapPagesHTML: true,
};

if (includeAlgolia == true) {
  siteConfig['algolia'] = {
    apiKey: '',
    // algolia ID TODO:
    indexName: 'pplbench',
  };
}

module.exports = siteConfig;
